version: "3.8"

services:

  mongo:
    image: mongo:7
    container_name: alertamascota-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: alertamascota

  backend:
    build: ./backend
    container_name: alertamascota-backend
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/alertamascota
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: alertamascota-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080

volumes:
  mongo_data:
