spring.application.name=alertamascota
server.port=8080

# MongoDB - cambia esta URI si usas Atlas o credenciales propias
spring.data.mongodb.uri=mongodb://mongo:27017/alertamascota

# CORS
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.com.alertamascota=DEBUG
